name: Runs only on pull requests to main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "ci/**"
jobs:
  integration-test:
    name: Run integration test on pull requests to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run integration tests
        run: ./mvnw clean integration-test
